/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 
 */

/**
 *
 * @author megha
 */
public class Menu extends javax.swing.JFrame {
    String ID;
        /** Creates new form Menu */
    public Menu() {
        initComponents();
    }
    public Menu(String id) {
        initComponents();
        ID = id;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        technical = new javax.swing.JRadioButton();
        GK = new javax.swing.JRadioButton();
        startTestBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Your Subject");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("ChiselD", 1, 36)); // NOI18N
        jLabel2.setText("WELCOME ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("chiselscript", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELECT YOUR SUBJECT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 30));

        technical.setBackground(new java.awt.Color(248, 246, 244));
        buttonGroup1.add(technical);
        technical.setFont(new java.awt.Font("Cushing Hv BT", 1, 24)); // NOI18N
        technical.setText(" techincal ");
        technical.setOpaque(false);
        technical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicalActionPerformed(evt);
            }
        });
        getContentPane().add(technical, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        GK.setBackground(new java.awt.Color(248, 246, 244));
        buttonGroup1.add(GK);
        GK.setFont(new java.awt.Font("Cushing Hv BT", 1, 24)); // NOI18N
        GK.setText("GK");
        GK.setOpaque(false);
        getContentPane().add(GK, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 70, -1));

        startTestBTN.setFont(new java.awt.Font("Curlz MT", 0, 18)); // NOI18N
        startTestBTN.setForeground(new java.awt.Color(0, 102, 102));
        startTestBTN.setText("START TEST >>");
        startTestBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(241, 236, 249), java.awt.Color.pink, new java.awt.Color(153, 0, 153), null));
        startTestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTestBTNActionPerformed(evt);
            }
        });
        getContentPane().add(startTestBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\India\\Desktop\\12.png")); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 400));

        jMenu1.setText("Select");

        jMenuItem1.setText("IP");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("GK");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");

        jMenuItem5.setText("Quit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startTestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTestBTNActionPerformed
        // TODO add your handling code here:
        String sub = null;
        if(technical.isSelected())
        {
            sub = "tech";
        }
        else if(GK.isSelected())
        {
            sub = "gk";
        }
        if (sub != null)
        {
            Test t = new Test(sub,ID);
            t.setVisible(true);
            this.setVisible(false);
        }
}//GEN-LAST:event_startTestBTNActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        technical.doClick();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        GK.doClick();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void technicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_technicalActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JButton startTestBTN;
    private javax.swing.JRadioButton technical;
    // End of variables declaration//GEN-END:variables

}
